# Generated by Django 5.1.7 on 2025-03-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
